### ISSUE TITLE
Sourcing help: 0.5 Ohm resistor

### ISSUE THREAD

**Issue by moarkaboom** [CrashOverride85/zc95#121]
I am having real trouble finding the correct part for C479296 which is a 0.5 Ohm Resistor used on the output board (R1, R26).
Can somebody either point so a supplier (preferably EU) or to a better available part?

Edit: I just discovered, these two Rs are already on the board, but on the BOM, they are under hand assembly? Am I missing somthing here?

![image](https://github.com/user-attachments/assets/2df35153-9f38-4db1-a1be-95818b0d02a4)

**Comment by CrashOverride85** [comment]
Hadn't noticed that was out of stock, I'll update it.

From LCSC, [C479327](https://www.lcsc.com/product-detail/Through-Hole-Resistors_VO-MF1W-0-5-2-6T63_C479327.html) would be a suitable replacement, or [MCKNP01SJ050KA10](https://uk.farnell.com/multicomp/mcknp01sj050ka10/res-0r5-5-1w-axial-wirewound/dp/1903704) from farnell.

The resistor is listed in the BoM file, and it seems C479296 is still in stock with jlcpcb, so if it wasn't un-ticked when ordering, jlcpcb would have assembled it. The main reason some parts are marked as hand assembly is because it is (or was, not checked recently) quite a bit cheaper.

**Comment by moarkaboom** [comment]
Thanks  for the response. Bur I don't need to source it now, right?

**Comment by CrashOverride85** [comment]
Nope :)
