### ISSUE TITLE
UT232A is out of stock most places, worth noting it on the BoM

### ISSUE THREAD

**Issue by jlatex** [CrashOverride85/zc95#45]
UT232A has been unavailable at LCSC for some time.  MAX3232CPE+ is a pin compatible alternative, I got mine from mouser as 700-MAX3232CPE.  It works.

**Comment by CrashOverride85** [comment]
In order to try and avoid having to order too many parts from different places, I think these two parts that LCSC sell are also pin compatible:
* C427446 - SIT SIT232EPE
* C968668 - XINLUDA XD3232

I'm going to order them and check they work, and update the BoM if they do. In the meantime, I'll list the MAX3232CPE+ as an alternative part.

**Comment by jlatex** [comment]
Also those are both significantly cheaper than the MAXIM part!
