### ISSUE TITLE
"ZC624 is not ready " issues when using the ZC-624 standalone

### ISSUE THREAD

**Issue by anonymous2nd** [CrashOverride85/zc95#78]
Hi guys, thanks for the great work first. Really well done.

I use the ZC-624 output module separately for a custom box. The module is connected to an ESP32 (Az-Delivery). 

I ordered 5 pcbs of the ZC-624  from JLC and got one working instantly. (This tells me that it's not an issue with my connection to the ESP32 or the connections)

The other 4 boards are assembled with exactly the same components (yes I use the correct mosfets) but none of them works.

When I run the demo firmware on the ESP32 I get the following message in the Serial Monitor:

MOSI: 23
MISO: 19
SCK: 18
SS: 5
ZC624 Version string: v1.6
Major version: 0
Minor version: 3
ZC624 is not ready (status = 1073500848)
Error: Zc624 is not ready. Stop.

What really confuses me is that the version string seems to be transmitted successfully via I2C. The major/minor version is a bit weird, but probably I overlooked something and 0.3 is correct? I expected 1.6 as maj.min. But then the scary stuff starts to begin. I checked the Raspi firmware and as far as I saw, it should either return 0, 1 or 2 but definitely not  1073500848 as the status. How is the version string correct but I2C transmits garbage as the status?

Another weird thing are the LED states. When I connect the 5V 3.3V and 5V LEDs glow. When I connect the 12V supply, the 12V LED glows and the 9V LED glows too but it only glows a short time and instantly fades then (capacitor?). The OK LED never glows. Should the 9V LED always glow when 12V is powered, or is this the expected behavior?

Do you guys have any idea how that can happen and how I can fix the boards? 

What I tried already:
- Different ESP32 and Raspberry Pico
- Flashing the firmware on both again
- Checking the connectivity outside of my normal module using breadboard

Thanks in regard. Keep up the great work.

PS: I'm using version 1.6 and I replaced the 50V 220uf capacitor with a 25V 220uf capacitor but that should be fine, right?

**Comment by CrashOverride85** [comment]
1. Major/minor versions
Yeah, that's right. It's more of an API version than a firmware version, and the ZC95 main board uses it to figure out if the zc624 version is compatible, without unnecessarily requiring an exact match.

2. 1073500848 state
That has to be a bug in the arduino library, I'll try and have a look at the weekend. It's reading an 8bit value, so anything over 255 is nonsense. I think it's just a display issue, and it it will be getting valid value, just not outputting it properly 

3. LED state
In v1.6, the OK LED does nothing (always off), so that's to be expected. It's more useful in v1.7, but I still need to update the arduino library to work with v1.7.

The 9v supply will be switched off if the zc624 fails it's self test, so that's most likely more a symptom of it failing its self test, rather than an issue itself, so yeah - kinda expected behaviour. 

4. Capacitor 
Yeah, a 25v rated one is fine

I would suggest taking a look at the zc624 trouble shooting notes:
https://github.com/CrashOverride85/zc95/blob/main/docs/Build.md#zc624-output-module

But if you connect up a 3.3v serial adapter (115k baud) to the output board, it should tell you why the self test is failing.

**Comment by CrashOverride85** [comment]
If you update the zc624 to v1.7 and use the new version of the arduino library, the state should be correctly reported, and the OK LED doing something more useful.

**Comment by CrashOverride85** [comment]
Nice, great to hear you've fixed it :)
The new FW & Arduino lib version shouldn't really make any difference if it's all working, but updating would at least give non-corrupted error messages if it goes wrong
